enum StateEnum {
    SPEAK = 'SPEAK',
    ASSISTANT = 'ASSISTANT',
    TOBACCO_STAGE_1 = 'TOBACCO_STAGE_1',
    TOBACCO_STAGE_2 = 'TOBACCO_STAGE_2',
    TOBACCO_STAGE_3 = 'TOBACCO_STAGE_3',
    TOBACCO_STAGE_4 = 'TOBACCO_STAGE_4',
    TOBACCO_STAGE_5 = 'TOBACCO_STAGE_5',
    TOBACCO_STAGE_6 = 'TOBACCO_STAGE_6',
}

export default StateEnum